### PR TITLE
Remove dependency on material components

### PR DESCRIPTION
**Pull request by rrva**
When upgrading from 0.2 to 0.7, we noticed that the library transistently depends on androidx, which will force us to migrate to androidx (which is a pretty big task). However, this dependency is not used in the library modules.

### CODE REVIEW

**Comment by wax911** [comment]
Oops, thank you. That was supposed to be in the sample/demo app only

**Comment by rrva** [comment]
Let me know when 0.8 is up

**Comment by rrva** [comment]
And thanks 👍

**Comment by wax911** [comment]
0.8 is up! Let me know how it goes :+1:

**Pull request merged**
